# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c4e847e050964ad6468f8e6b416e145fe70936223c75486a7a3dda7ef1752b01dd9df6451ccfa37f4dd650b667c387bf12028f6f5cadbc3cd03cad5f9e002a5

test:
  secret_key_base: b344ebfe4d70ac0b534d20b218be4efece2bcf18a37c8589bc4f25f5bc3c56afef13a94f81153ed2ee1fc087db65f7f25514f52dc1966bd5c8367ef009498079

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
